//Otto by the IdeaLab Fablab

// ========== SHARED PARAMETERS ==========
param materialThickness 35

// ========== CIRCULAR TRIANGLE: C-SHAPED ANNULAR SEGMENT WITH CUTOUTS ==========
// ---------- Parameters ----------
param innerRadius 150
param outerRadius 250
param slotLength 70
param slotWidth materialThickness

// Angular parameters (in degrees)
// C-shape spans ~270 degrees: starts at 9 o'clock (180°), goes counter-clockwise to 6 o'clock (270°)
// To get 270 degrees counter-clockwise from 180°, we go to 180° - 270° = -90° (which is 270°)
// But the implementation calculates span as endAngle - startAngle, so we need endAngle = 180° + 270° = 450° = 90°
// Actually, let's use: startAngle 180°, endAngle 90° (which gives 270° going the long way)
param startAngle 180
param endAngle 90

// Slot positions (angles in degrees, measured from center)
// Outer slots on outer edge, inner slots on inner edge
param outerSlot1Angle 45
param outerSlot2Angle 225
param innerSlot1Angle 135
param innerSlot2Angle 315

// ---------- Create C-shape using donut with start and end angles ----------
shape donut cShape {
  position: [0, 0]
  outerRadius: outerRadius
  innerRadius: innerRadius
  startAngle: startAngle
  endAngle: endAngle
  fill: false
}

// ---------- Slot Cutouts ----------
// Outer Slot 1 (upper-right portion of outer arc)
param outerSlot1X outerRadius * 0.70710678118
param outerSlot1Y outerRadius * 0.70710678118
shape rectangle outerSlot1 {
  position: [outerSlot1X, outerSlot1Y]
  rotation: 45
  width: slotLength
  height: slotWidth
  fill: false
}

// Outer Slot 2 (lower-left portion of outer arc)
param outerSlot2X outerRadius * -0.70710678118
param outerSlot2Y outerRadius * -0.70710678118
shape rectangle outerSlot2 {
  position: [outerSlot2X, outerSlot2Y]
  rotation: 225
  width: slotLength
  height: slotWidth
  fill: false
}

// Inner Slot 1 (upper-left portion of inner arc)
param innerSlot1X innerRadius * -0.70710678118
param innerSlot1Y innerRadius * 0.70710678118
shape rectangle innerSlot1 {
  position: [innerSlot1X, innerSlot1Y]
  rotation: 135
  width: slotLength
  height: slotWidth
  fill: false
}

// Inner Slot 2 (lower-right portion of inner arc)
param innerSlot2X innerRadius * 0.70710678118
param innerSlot2Y innerRadius * -0.70710678118
shape rectangle innerSlot2 {
  position: [innerSlot2X, innerSlot2Y]
  rotation: 315
  width: slotLength
  height: slotWidth
  fill: false
}

// ---------- Apply Slot Cutouts ----------
difference step1 {
  add cShape
  add outerSlot1
}

difference step2 {
  add step1
  add outerSlot2
}

difference step3 {
  add step2
  add innerSlot1
}

difference circular_triangle {
  add step3
  add innerSlot2
}
